[package]
name = "strobilus-core"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.22.2"

[dependencies]
cedar-policy-core = { workspace = true }
lalrpop-util = "0.22.2"
parking_lot = "0.12.5"
smol_str = "0.3.2"
thiserror = "2.0.12"
tokio = { version = "1.40", features = ["rt"] }
