[workspace]
resolver = "2"

members = [
    "crates/strobilus",
    "crates/strobilus-core"
]

[workspace.dependencies]
cedar-policy-core = { git = "https://github.com/strobilus-lang/cedar.git", branch = "strobilus-main" }

[patch.crates-io]
cedar-policy-core = { git = "https://github.com/strobilus-lang/cedar.git", branch = "strobilus-main" }
